# Copyright 2024 Caroline Blank <caro@c-space.org>
# Copyright 2024 Remy Blank <remy@c-space.org>
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Update system package index
        run: sudo apt-get update
      - name: Install system packages
        run: |
          sudo apt-get install --yes \
              graphviz
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python packages
        run: |
          pip install \
              myst-parser==3.0.1 \
              sphinx==7.3.7 \
              sphinx-book-theme==1.1.3 \
              sphinx-copybutton==0.5.2 \
              sphinx_design==0.6.0 \
              sphinx-exercise==0.4.1 \
              sphinx-proof==0.1.3 \
              sphinx-togglebutton==0.3.2
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Checkout common repository
        uses: actions/checkout@v4
        with:
          repository: t-docs/common.git
          ref: main
          path: common
      - name: Build HTML
        run: make -C repo html
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: repo/docs/_build/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
