# Copyright 2024 Caroline Blank <caro@c-space.org>
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

name: Publish
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    name: Publish
    uses: t-doc-org/common/.github/workflows/deploy-github-pages.yml@main
    secrets: inherit
